import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { createExpense } from "../providers/ExpenseApi";
import { Expense } from "../interfaces/Expense";

function CreateExpensePage() {
  const [description, setDescription] = useState("");
  const [category, setCategory] = useState("");
  const [amount, setAmount] = useState(0);
  const [submitting, setSubmitting] = useState(false);

  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);

    const newExpense: Expense = {
      id: 0, // Temporary ID, should be generated by the server
      description: description.trim(),
      category: category.trim(),
      amount: amount,
      date: new Date(),
    };

    try {
      await createExpense(newExpense);
      navigate("/ExpenseList"); // Redirect to the main page after creating the task
    } catch (error) {
      console.error("Error creating expense:", error);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="container mt-5">
      <h2 className="mb-4 text-center">Create New Expense</h2>
      <form onSubmit={handleSubmit} className="mt-4">
        <div className="mb-3">
          <label htmlFor="description" className="form-label">
            Description
          </label>
          <input
            type="text"
            className="form-control"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            required
            disabled={submitting}
          />
        </div>

        <div className="mb-3">
          <label htmlFor="category" className="form-label">
            Category
          </label>
          <input
            type="text"
            className="form-control"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            required
            disabled={submitting}
          ></input>
        </div>

        <div className="mb-3">
          <label htmlFor="amount" className="form-label">
            Amount
          </label>
          <input
            type="number"
            className="form-control"
            value={amount}
            onChange={(e) => setAmount(parseFloat(e.target.value))}
            required
            disabled={submitting}
          ></input>
        </div>

        <button type="submit" className="btn btn-primary" disabled={submitting}>
          {submitting ? "Creating..." : "Create Expense"}
        </button>
      </form>
    </div>
  );
}

export default CreateExpensePage;
